services:
  yugabyte:
    image: yugabytedb/yugabyte:latest
    container_name: yugabyte-node
    network_mode: host
    restart: unless-stopped
    profiles: ["db", "dev"]
    volumes:
      - ./yugabyte_data:/home/yugabyte/yb_data:z
    command:
      - bin/yugabyted
      - start
      - --advertise_address=${MY_IP}
      - --join=${LEADER_IP}
      - --base_dir=/home/yugabyte/yb_data
      - --background=false
      - --fault_tolerance=zone

  app:
    build:
      context: ./app
      target: development
    network_mode: host
    volumes:
      - ./app:/app:z
      - /app/node_modules
      - /app/.next
    depends_on:
      yugabyte:
        required: false
        condition: service_started
    environment:
      - NODE_ENV=development
      - DB_HOSTS=${DB_HOSTS}
      - YB_DATABASE=${YB_DATABASE}
      - YB_USER=${YB_USER}
      - YB_PASSWORD=${YB_PASSWORD}
    profiles: ["app", "dev"]
    restart: unless-stopped
